---
- name: ParseReceivedSMS
  cmd: "su-exec root docker exec raspisms_apache_1 /var/www/html/RaspiSMS/console.php -c parseReceivedSMS"
  time: "0 *"
- name: SendScheduleds
  cmd: "su-exec root docker exec raspisms_apache_1 /var/www/html/RaspiSMS/console.php -c SendScheduleds"
  time: "0 *"
